### ISSUE TITLE
Unsure how it works.

### ISSUE THREAD

**Issue by trebmuh** [cosmocode/dokuwiki-plugin-cleanup#7]
Hi , after reading to the doc, it does look to be a plugin that I would use. That said, I'm a bit unsure how it works.
My point looking for such a plugin is to be able to remove pictures (mainly) that are not used anymore. Could you please confirm that this plugin will do this job ?
Thanks.

**Comment by splitbrain** [comment]
That's the what the orphaned media part will do.

**Comment by trebmuh** [comment]
So, I assume you are talking of the "mediaatticage (Delete old media revisions after this time (seconds)" option. By default, it is set up to "60*60*24*30*1" which is equal to one month. Then, if I'm putting something like : "60*60*24*1" it will delete non-used media every day (assuming that the "runautomatically" is ticked), right ? If you do agree to that, I'll be putting this example on the doc since while reading at it, it is a bit confusing (at least for me).
